### PR TITLE
Add connected apps link when deleting source with apps

### PR DESCRIPTION
**Pull request by rvsia**
**Description**

Connected apps is now link which leads... to connected apps! :tada: :taco: :tada: 

connected_apps
(mouse is missing :mouse: :dagger: :skull_and_crossbones: )

@terezanovotna @Hyperkid123

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@rvsia i am amazed that you can navigate the UI with transparent mouse. :open_mouth:

**Comment by rvsia** [comment]
@Hyperkid123 :ghost:

**Comment by terezanovotna** [comment]
Nice!

**Comment by slemrmartin** [comment]
Nice! That was very annoying when I tested deleting before :)

**Pull request merged**
