### PR TITLE
Remove application

### PR DESCRIPTION
**Pull request by rvsia**
**Description**

- Adds Remove app
- Add application becomes Manage Applications

Manage application

image

Warning

image

Loading

image

Message

image

Error message

image

TODO

- [x] catch messages
- [x] tests

@terezanovotna

### CODE REVIEW

**Comment by terezanovotna** [comment]
I suggest using a modal to ask this question - that way we follow patternfly.

"Are you sure to remove "source name" from this application?"
"Remove", "Cancel"

**Comment by terezanovotna** [comment]
clap clap. looks great. awesome job!

**Comment by rvsia** [comment]
Also edit a button to final step of the creating app to make easier multiple additions of apps

image

**Comment by terezanovotna** [comment]
Nice!!!

better wording for warning:
"Are you sure you want to remove Catalog from this source?"

**Comment by rvsia** [comment]
@miq-bot remove_label unmergeable, wip

**Comment by rvsia** [comment]
@Hyperkid123

**Pull request merged**
